import { ITableData } from '../interfaces/interfaces';

export const mockTableData: Array<ITableData> = [
  {
    capId: '1/23568',
    manufacturer: 'Mazda',
    model: '1 Series',
    bodyType: 'Saloon',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Published',
  },
  {
    capId: '1/23568',
    manufacturer: 'Honda',
    model: 'Civic',
    bodyType: 'Saloon',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Ready to publish',
  },
  {
    capId: '1/23568',
    manufacturer: 'Audi',
    model: 'A4',
    bodyType: 'Saloon',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Ready to publish',
  },
  {
    capId: '1/23568',
    manufacturer: 'Toyota',
    model: '1 Series',
    bodyType: 'Saloon',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Published',
  },
  {
    capId: '1/23568',
    manufacturer: 'Mercedes-Benz',
    model: 'S Class',
    bodyType: 'Saloon',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Draft',
  },
  {
    capId: '1/23568',
    manufacturer: 'Chevrolet',
    model: '1 Series',
    bodyType: 'Saloon',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Draft',
  },
  {
    capId: '1/23568',
    manufacturer: 'BWM',
    model: 'M-Series',
    bodyType: 'Saloon',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Draft',
  },
  {
    capId: '1/23568',
    manufacturer: 'Hyundai',
    model: 'Accent',
    bodyType: 'Saloon',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Published',
  },
  {
    capId: '1/23568',
    manufacturer: 'Fiat',
    model: 'Bravo',
    bodyType: 'Hatchback',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Ready to publish',
  },
  {
    capId: '1/23568',
    manufacturer: 'Ford',
    model: 'GT',
    bodyType: 'Coupe',
    modelDescription: '118i [136] M Sport 5 Doors Step Auto [LCP]',
    status: 'Published',
  },
];
